import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Container, Text } from '@nextui-org/react';

import styles from '../../styles/Home.module.css';
import { fetchExhibitionDetail } from '../../src/features/exhibition/exhibitionAPI';
import { Exhibition } from '../../src/features/exhibition/exhibitionModel';

interface ExhibitionDetailProps {
  data: Exhibition;
}

const ExhibitionDetail: NextPage<ExhibitionDetailProps> = ({ data }) => {
  return (
    <Container>
      <Head>
        <title>Exhibition Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text
          h1
          size={60}
          css={{
            textGradient: '45deg, $blue500 -20%, $pink500 50%',
          }}
          weight="bold"
        >
          {data.title}
        </Text>
        <img src={data.image_url} alt={data.title} width={500} height="auto" />
        <p>{data.description}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Container>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  const id = params?.id as string;
  // Fetch data from external API
  const data = await fetchExhibitionDetail(id);

  // Pass data to the page via props
  return { props: { data: data.data } };
};

export default ExhibitionDetail;
